
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")
print("gdrtstdtdr")